### ISSUE TITLE
fix placeholder text in draft.js editor

### ISSUE THREAD

**Issue by sit79** [graduates11/journal-app#130]
It's difficult for the user to see _where_ to click to actually start typing a note. That should be solved either by styling or by creating a functioning placeholder text that can actually be clicked.

**Comment by martynakrysinska** [comment]
![Screen Shot 2019-08-02 at 13 22 32](https://user-images.githubusercontent.com/34917508/62366972-a1d63480-b528-11e9-9691-b5f629ec6fb1.png)

**Comment by martynakrysinska** [comment]
closed
