### ISSUE TITLE
research hashtags

### ISSUE THREAD

**Issue by sit79** [graduates11/journal-app#37]
Could hashtags be implemented instead normal tags, such that the user could create a hashtag by just writing it in the text of an entry? ("#exampleHashTag")

**Comment by sit79** [comment]
This https://www.draft-js-plugins.com/plugin/hashtag might come in handy. @martynakrysinska you should have a look at it. Would it complicate the editor very much in its current setup? Or should we exclude this enhancement for now?

**Comment by martynakrysinska** [comment]
closed #52
