### ISSUE TITLE
write tests

### ISSUE THREAD

**Issue by martynakrysinska** [graduates11/journal-app#60]
https://jestjs.io/docs/en/configuration
https://medium.com/@JeffLombardJr/organizing-tests-in-jest-17fc431ff850
https://medium.com/javascript-scene/unit-testing-react-components-aeda9a44aae2
https://www.valentinog.com/blog/testing-react/

happy testing

**Comment by sit79** [comment]
At this point, writing tests seems pointless, unless we write them for CircleCI's continuous integration process for future improved versions of this software.

**Comment by sit79** [comment]
No point to do it at this point. Also writing tests for react hooks is still a very tricky thing.
